### PR TITLE
Support Jest 18

### PR DESCRIPTION
**Pull request by aaronjensen**
It appears that reporters are now meant to pass the results along.

### CODE REVIEW

**Comment by ToshB** [comment]
Just stumbled upon the same problem myself, it's a good fix.

**Comment by winterbe** [comment]
Can you provide more information on this? 

I just updated my project to Jest 18 and everything seems to work fine.

**Comment by aaronjensen** [comment]
Run watch without team city flag. You should see an errror.

**Comment by aaronjensen** [comment]
Thanks for the merge. Could you please ping here after you've had a chance to release a new version so we can upgrade? Thanks!

**Comment by winterbe** [comment]
@aaronjensen Sorry for the delay. I've published version 0.3.0 including your changes.

**Pull request merged**
