### PR TITLE
used path separator instead of  /

### PR DESCRIPTION
**Pull request by pitermarx**

### CODE REVIEW

**Comment by winterbe** [comment]
Thanks.

**Comment by pitermarx** [comment]
Could you release this on npm?

**Comment by winterbe** [comment]
I'm on holiday, will publish to NPM next Tuesday.

**Comment by winterbe** [comment]
@pitermarx I've published version 0.2.0 to NPM including your changes.

**Comment by pitermarx** [comment]
awesome. thanks

**Pull request merged**
